### ISSUE TITLE
Add usage guides to docs.etebase.com

### ISSUE THREAD

**Issue by tasn** [etesync/etebase-rs#12]
As the title says, it would be great to have Rust examples in https://docs.etebase.com
The repo for the docs is available here: https://github.com/etesync/etebase-docs/

There are already docs for other languages, so it's just a matter of doing the same, but for Rust.

**Comment by geovie** [comment]
Just found this 😊 I'm working on it in https://github.com/etesync/etebase-docs/pull/10

**Comment by tasn** [comment]
Yeah, I know. :heart_eyes: 
Please mention this ticket in the main description in https://github.com/etesync/etebase-docs/pull/10 so it's included in the merge commit. Thanks a lot!
