### ISSUE TITLE
Creating a new etebase client succeeds for URL localhost:<port>

### ISSUE THREAD

**Issue by shashwatjolly** [etesync/etebase-rs#8]
## Description
When passing localhost:<port> to etebase_client_new in libetebase (without http:// or https://), it succeeds, and so, doesn't set the ETEBASE_ERROR_CODE_URL_PARSE to the error code.
It works as expected for localhost though.

## Expected behaviour
It should fail for all URLs without http:// and https://, including localhost:<port>.

**Comment by djmitche** [comment]
It looks like this issue should actually be on https://github.com/etesync/libetebase, if anything?

**Comment by tasn** [comment]
No, it's correct (he asked me before opening this). This repo is what powers libetebase and the issue is here.
